# Generated by Django 4.1.7 on 2023-03-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='donor_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='executing_agency_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='sector_id',
        ),
        migrations.RemoveField(
            model_name='commitmentdisbursement',
            name='agreement_id',
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.agreement'),
        ),
        migrations.AddField(
            model_name='project',
            name='commitment_disbursement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.commitmentdisbursement'),
        ),
        migrations.AddField(
            model_name='project',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.donor'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.sector'),
        ),
    ]
