# Generated by Django 4.1.7 on 2023-03-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_agreement_donor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commitment_disbursement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.commitmentdisbursement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.donor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.sector'),
        ),
    ]
