# Generated by Django 4.1.7 on 2023-03-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_agreement_agreement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='task_app.province'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='task_app.district'),
        ),
        migrations.AlterField(
            model_name='project',
            name='agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='task_app.agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commitment_disbursement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_disbursement', to='task_app.commitmentdisbursement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='task_app.donor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='municipality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='task_app.municipality'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='task_app.sector'),
        ),
    ]
