# Generated by Django 4.1.7 on 2023-03-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_district_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='district_id',
            new_name='district',
        ),
    ]
