# Generated by Django 4.1.7 on 2023-03-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_rename_district_id_municipality_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='agreement_id',
            new_name='agreement',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='commitment_disbursement_id',
            new_name='commitment_disbursement',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='municipality_id',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sector_id',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='projectexecutingagency',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectimplementingpartner',
            old_name='implementing_partnet_id',
            new_name='implementing_partnet',
        ),
        migrations.RenameField(
            model_name='projectimplementingpartner',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectsector',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectsector',
            old_name='sector_id',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='projecttypeofassistance',
            old_name='project_id',
            new_name='project',
        ),
    ]
