# Generated by Django 4.1.7 on 2023-03-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_rename_agreement_id_project_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='donor_id',
            new_name='donor',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.district'),
        ),
    ]
