# Generated by Django 4.1.7 on 2023-03-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_rename_donor_id_project_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimplementingpartner',
            name='implementing_partnet',
        ),
        migrations.RemoveField(
            model_name='projectimplementingpartner',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectsector',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectsector',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='projecttypeofassistance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttypeofassistance',
            name='type_of_assistance_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sector',
        ),
        migrations.AddField(
            model_name='project',
            name='executing_agency',
            field=models.ManyToManyField(to='task_app.executingagency'),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_partner',
            field=models.ManyToManyField(to='task_app.implementingpartner'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_sector',
            field=models.ManyToManyField(to='task_app.sector'),
        ),
        migrations.AddField(
            model_name='project',
            name='type_of_assistance',
            field=models.ManyToManyField(to='task_app.typeofassistance'),
        ),
        migrations.DeleteModel(
            name='ProjectExecutingAgency',
        ),
        migrations.DeleteModel(
            name='ProjectImplementingPartner',
        ),
        migrations.DeleteModel(
            name='ProjectSector',
        ),
        migrations.DeleteModel(
            name='ProjectTypeOfAssistance',
        ),
    ]
