# Generated by Django 4.1.7 on 2023-03-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_remove_projectimplementingpartner_implementing_partnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='task_app.agreement'),
        ),
    ]
