# Generated by Django 4.1.7 on 2023-03-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_project_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='counterpart_ministry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_ministry', to='task_app.counterpartministry'),
        ),
        migrations.AlterField(
            model_name='counterpartministry',
            name='counterpart_ministry_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='executingagency',
            name='executing_agency_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='implementingpartner',
            name='implementing_partner_name',
            field=models.CharField(max_length=1000),
        ),
    ]
