# Generated by Django 4.1.7 on 2023-03-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_alter_typeofassistance_type_of_assistance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartministry',
            options={'verbose_name_plural': 'Counter Ministries'},
        ),
        migrations.AlterModelOptions(
            name='executingagency',
            options={'verbose_name_plural': 'Executing Agencies'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'Municipalities'},
        ),
    ]
